site_name: Fischer Archiv
docs_dir: artikel
repo_url: https://github.com/DEIN_NUTZERNAME/DEIN_REPO
repo_name: Zum GitHub-Repository

hooks:
  - hooks.py

plugins:
  - search
  - offline
  - callouts # Callouts [!info] übersetzen in Admonition (!!! info)
  - section-index
  - literate-nav

markdown_extensions:
  - admonition # Infoboxen (!!! info) für wichtige Hinweise
  - pymdownx.details # Ausklappbare Boxen (??? info) zum Platzsparen
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences # Bessere Code-Blöcke & Verschachtelung von Boxen
  - md_in_html # Markdown-Rendering innerhalb von HTML-Tags erlauben

use_directory_urls: false

theme:
  name: material
  language: de
  features:
    - search.fixed
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tabs # Setzt die Hauptkategorien in eine obere Leiste
    - navigation.tabs.sticky # Hält die obere Leiste fest
    - navigation.top # "Back to Top" Button für lange Seiten

  # Dark/Light Mode Switch (System-Standard als Basis)
  palette:
    # Schema für hellen Modus
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Zum dunklen Modus

    # Schema für dunklen Modus
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Zum hellen Modus
